### ISSUE TITLE
question : is it possible to have a larger loader

### ISSUE THREAD

**Issue by mastermind1981** [jfeigel/ngLoader#2]
I have tried to modify the  loader-container class to have a bigger loader overlay ( the spinner and the black background) but actually it doesn't work.

Here is the new class, i used:

```

.loader-container {
  height: 200px;
  width: 100%;
  position: relative;
  border: 1px solid #CCCCCC;
  overflow: hidden;
}
```

Is it possible to do have a larger loader?

Thanks in advance,

**Comment by jfeigel** [comment]
The `loader-container` class is just for the example. You can overwrite or add styles to the `loader-content` class in order to adjust the styles of the actual loader.
